spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.74.131:7001
        - 192.168.74.131:7002
        - 192.168.74.131:7003
        - 192.168.74.131:7004
        - 192.168.74.131:7005
        - 192.168.74.131:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.74.132
    password: 1111
    port: 5672
    username: admin
    virtual-host: /
    publisher-confirms: true #开启消息确认回调
    publisher-returns: true #开启消息退回回调
    listener:
      direct:
        acknowledge-mode: "manual"
      simple:
        acknowledge-mode: "manual"

server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
